version: '3.5'
services:
  mysql:
    image: mysql:8.0.27
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    restart: always
    env_file: .env
    ports:
      - '${MYSQL_EXTERNAL_PORT}:${MYSQL_INTERNAL_PORT}'
    expose:
      - '${MYSQL_INTERNAL_PORT}'
    volumes:
      - ./mysql-data:/var/lib/mysql

#  discord_display_bot:
#    build:
#      context: .
#      target: discord_display_bot
#    env_file: .env

#  orders_creator:
#    container_name: orders_creator
#    build:
#      context: .
#      target: orders_creator
#    restart: always
#    env_file: .env
#
#  orders_monitoring:
#    container_name: orders_monitoring
#    build:
#      context: .
#      target: orders_monitoring
#    restart: always
#    env_file: .env
